name: Release

on:
  push:
    tags:
      - '*.*.*'
    paths:
      - 'Wax.nuspec'

jobs:
  publish:
    name: Publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup version from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/}" >> $GITHUB_ENV

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Package the template
        run: nuget pack Wax.nuspec -NoDefaultExcludes -Version ${VERSION}

      - name: Publish to nuget.org
        run: nuget push *.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}} -SkipDuplicate